name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 0.12.2
homepage: https://github.com/brianegan/chewie

publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  ext_video_player:
    path: ../ext_video_player-0.0.4
  wakelock: ^0.2.1+1
  share:
  intl:
  subtitle_wrapper_package:
    path: ../subtitle_wrapper_package-1.0.4
  file_picker:
  url_launcher:
  flutter_ffmpeg:
  path:
  path_provider:
  jidoujisho:
    path: ../
  audioplayers:
  flutter_vlc_player: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.1

flutter:
  uses-material-design: true
