name: chewie_fork
description: A video player for Flutter with Cupertino and Material play controls
version: 0.12.2
homepage: https://github.com/brianegan/chewie

publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"

dependencies:
  audioplayers:
  flutter:
    sdk: flutter
  flutter_ffmpeg:
  flutter_vlc_player:
  intl:
  jidoujisho:
    path: ../
  path:
  path_provider:
  share:
  shared_preferences:
  subtitle_wrapper_package:
    path: ../subtitle_wrapper_package
  url_launcher:
  wakelock:
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.1

flutter:
  uses-material-design: true
